<x-guestLayout>
    @section('social_description', 'Um Olhar sobre o Irão')
    @section('social_image', '/stories/2024/11/irao1998.jpg')

    <x-margins-text>
        <h1>Porto >> Ilha de Ormuz >> Porto</h1>

        <img src="/stories/2024/11/irao1998.jpg" class="h-56 my-8 m-auto" alt="Um Olhar sobre o Irão">

        <h1>A Viagem</h1>


        <h2>Um Olhar sobre o Irão</h2>

        <p>Porto, 5 horas da manhã, partimos para a 1ª etapa , com 2900 km de ligação a Bari no sul de Itália com destino ao Irão. Começa assim a nossa viagem ,que surge como uma alternativa ao projecto inicial, idealizado já em 1997, de ligar em motociclo Macau ao Porto, mas que por dificuldades várias não se pode concretizar. Findos 2 dias e meio, estávamos no ferry de nome " Sea Serenade ", tinha sido um baleeiro nas águas do império do sol nascente e depois transformado num barco que fazia carreiras regulares no mediterrâneo, e nos levaria até Cesme na Turquia.</p>

        <h2>Républica da Turquia</h2>

        <ul>
            <li>Capital: Ancara</li>
            <li>Moeda: Lira Turca</li>
            <li>Língua Oficial: Turco</li>
        </ul>

        <p>Após as fastidiosas burocracias da alfândega em Cesme, começamos a nossa segunda etapa com 2800 km de ligação até ao posto fronteiriço de Guburlak, situado no norte da Turquia. A policia de Cesme tinha-nos avisado que a nossa passagem pelo curdistão não ia ser fácil, pois na semana anterior os guerrilheiros do PKK tinham morto três soldados. Esta tirada iria revelarmos algumas surpresas, a começar pela imensidão dos planaltos na Anatolia Central e das suas longas rectas ,algumas com 20 e 30 km de extensão.</p>

        <h2>Curdistão Zona de Guerra</h2>

        <p>Tínhamos entrado em território curdo, primeiro controle militar à entrada da cidade de Elazig. Fomos convidados a beber chá de maça, pelo simpático comandante da guarnição acompanhados por mais um oficial e uma agente da policia secreta. Após uma amena conversa na qual o comandante disse possuir uma Jawa 350, convidamo-lo a ele e à mulher da policia secreta, a dar uma volta nas BMW R1100 GS. Eles aceitaram e no final estavam eufóricos… tínhamos feito amizade! Como se não bastasse indicaram-nos um hotel onde deveríamos ficar, pois de forma amável informaram-nos que não deveríamos seguir viagem durante a noite, já que as montanhas não ofereciam segurança. Chegados ao hotel, já os militares tinham telefonado a combinar o preço e a informar a recepção que éramos seus amigos.</p>
        <p>Na manhã seguinte o objectivo era chegar à fronteira turco-iraniana. Partimos... mas logo à saída da cidade outro controle militar! Fomos convidados a tomar chá, e começamos a duvidar sobre se realmente conseguiríamos atingir o nosso objectivo, pois se em todos os postos militares bebessemos chá iria ser difícil. Lá fomos passando por vários postos militares e eis quando aparece na estrada um homem uniformizado com a arma a tiracolo. Olhamos e ficamos sem saber se seria um militar turco ou um guerrilheiro do PKK. Prosseguimos... e uns quilómetros mais à frente aparece outro.Desfizeram-se então as nossas duvidas. Este apenas trazia um blusão militar. Continuamos e por força do destino tivemos que parar pois um rebanho de cabras resolveu atravessar a estrada. Nesse preciso momento olhamos para o lado e vimos o pastor armado de AK 47 mais conhecida por Kalashnikov! Lá continuamos pela estrada a pensar no que tínhamos visto. Seriam guerrilheiros do PKK ou civis armados pelos militares.</p>
        <p>Seguimos até Guburlak tendo passado por vinte e quatro postos militares e apenas tomado chá em seis. Nada mau!</p>
        <p>Chegados ao posto de fronteira turca com o Irão fomos logo rodeados pelos indivíduos do mercado negro. Aproveitamos para saber o câmbio do mercado negro: 1 dolar/5500 rials, quase o dobro do cambio oficial: 1 dolar/3000 rials. Depois de termos todos os documentos, o oficial turco desejou-nos boa sorte e rolamoslentamente para o posto fronteiriço iraniano.</p>
        <p>À medida que nos íamos aproximando começamos a ver a fronteira de Bazargan, famosa desde os tempos remotos por ali passar a Rota da Seda que ligava o oriente ao ocidente, e nos anos 60/70 por ali também passar a rota utilizada pelos hippyes que da Europa se dirigiam a Katmandu no Nepal.</p>

        <h2>Républica Islamica do Irão</h2>

        <ul>
            <li>Capital: Teerão</li>
            <li>Moeda: Rial</li>
            <li>Língua Oficial: Persa</li>
        </ul>

        <p>Chegamos a Bazargan, um guarda fronteiriço indicou-nos o local onde devíamos parar as BMW. Começamos logo a pensar que iríamos passar ali a noite , pois a quantidade de pessoas que se encontravam no posto era enorme.</p>
        <p>Entretanto apareceu um funcionário do "turisme office", que nos conduziu ao local próprio para tratar das burocracias. Eis que surge um sujeito a quem o funcionário do "turisme office" chamou de " Big Chief "; era o director dos "customs". Surpreso, pois era a primeira vez que portugueses passavam por Bazargan, desejou-nos uma boa estadia no Irão à qual respondemos "motasshakkeram" que significa obrigado.</p>
        <p>Passados alguns minutos tínhamos os passaportes connosco e começava aqui a grande virtude do povo do Irão: Hospitalidade! Aproveitamos para trocar algum dinheiro a um cambio acima do valor oficial e às dezanove horas e vinte e quatro minutos passamos os portões que davam acesso a cidade de Bazargan.</p>

        <h2>Trânsito Sem Regras</h2>
        <p>O nosso objectivo era chegar a Tabriz no Azerbeijão Iraniano, mas passados alguns quilómetros vimos que iria ser impossível chegar nesse dia, pois continuávamos com controles, não militares como na Turquia, mas da guarda da revolução Islâmica: Passport? Where do you come from? Motocicle mark? Ao que nós respondíamos: Portugal, BMW e lá faziam sinal para seguirmos, ao que nós retorquiamos timidamente: "Salãm aleikom", que em português significa: A paz esteja convosco. Entretanto escurecera e tornava-se difícil conduzir, pois não existiam regras de transito; circulávamos com transito no sentido inverso pela esquerda e frequentemente pela direita, era incrível como não tínhamos ainda visto nenhum acidente. Paramos numa bomba de gasolina para encher os depósitos. No final pagamos quatro mil rials por vinte litros, o que equivalia a um preço de sete escudos por litro... que saudades de Portugal...! Estávamos ainda a cento e trinta quilómetros de Tabriz, decidimos continuar até Marand,onde pernoitamos.</p>
        <p>Na manhã seguinte seguimos para Tabriz, queríamos ver a mesquita azul "Masjed-é Kabud", datada de 1465, fortemente danificada por vários terramotos, mas ainda possuidora de um notável e extenso trabalho de azulejaria, com mosaicos azuis no portal e escrita farsi em dourado.</p>

        <h2>Mar Cáspio</h2>
        <p>Prosseguimos para o Mar Cáspio, onde passamos pelas montanhas num sobe e desce continuo, com alguns sustos pela estrada; à saída duma curva quatro camiões tanques a ultrapassarem-se uns aos outros. Nem queríamos acreditar no que víamos. Cada vez mais circulávamos encostados à berma, era um risco aceitável.</p>
        <p>Chegamos a Astara, cidade fronteiriça com a antiga Republica Soviética do Azerbeijão. O calor e a humidade tinham aumentado e sentíamos toda a roupa colada ao corpo..., era uma sensação estranha.</p>
        <p>Prosseguimos pela costa em direcção a Bandar-é Anzali, cidade onde pernoitamos e onde os russos em 1800 tinham estabelecido um posto comercial. A influência russa é notória ainda, principalmente na arquitectura dos edifícios. De manhã cedo partimos pela estrada junto à costa do Mar Cáspio, aproveitamos para tomar um banho, pois o calor já apertava.</p>

        <h2>Travessia Arriscada</h2>
        <p>Seguimos depois por uma estrada secundária com destino a Chalus , mas qual o nosso espanto quando a estrada terminava num rio. A ligação entre as duas margens do rio Sividro era feita por um pequeno barco. Pensamos que não ia ser possível colocar as BMW no exíguo espaço existente, mas depressa nos apercebemos do profissionalismo do barqueiro. Colocamos uma prancha de um lado ao outro e outra a fazer de rampa e conseguimos colocá-las de maneira a atravessar o rio para a outra margem. Entretanto começaram a juntar-se pessoas que esperavam para fazer a travessia seguindo atentamente as nossas manobras para tirar as BMW do barco e ajudavam com sorrisos simpáticos e contagiantes.</p>

        <h2>Montanhas Alborz</h2>
        <p>Continuamos até Chalus para apanhar a estrada para as montanhas Alborz com destino à aldeia de Delir, situada a cerca de quatro mil metros de altitude. Saímos do asfalto para uma pista que nos levaria até Delir a cerca de trinta quilómetros, onde não havia luz.</p>
        <p>Prosseguimos pela pista sempre a subir as montanhas.Chegamos a Delir já de noite e por sorte encontramos um habitante a quem por meio de alguma mímica, fizemos saber que procurávamos um local para comer e dormir. Fez sinal para o seguirmos e levou-nos para sua casa. Chamava-se Sirzat. Paramos as BMW debaixo da varanda da habitação, tiramos as botas à entrada e fomos recebidos pelo pai e por um amigo, pois como é costume as mulheres estavam numa outra sala. Presentearam-nos com um jantar digno de um rei. Estávamos cansados, pois fazer parte da pista durante a noite exigia grande concentração na condução. No final do jantar aproveitamos para oferecer cigarros portugueses e também nos ofereceram cigarros iranianos da marca 57. Ouvimos todos música portuguesa dos MadreDeus, da qual por sinal gostaram. Entretanto começaram a preparar a sala para pernoitarmos, trouxeram os colchões e mantas para nos agasalharmos e adormecemos rapidamente.</p>
        <p>No dia seguinte da manha ofereceram-nos o pequeno-almoço, e qual o nosso espanto quando toda a família, Pai, Mãe, Irmã, Mulher e Filha de Sirzat, entram na sala e nos observam enquanto comiamos o pequeno-almoço. Saímos para fora da habitação e vimos e ouvimos o rio que passava a poucos metros.</p>
        <p>Entretanto para nosso prazer começaram a chegar vizinhos, entre quais mulheres, algumas delas bem atrevidas na maneira como se riam de nós, com um olhar muito maroto. Podemos observar a maneira de vestir diferente dos habitantes das montanhas (roupas com cores garridas e nenhuma delas usava o tradicional chador negro, mas sim colorido). Por fim tivemos de nos despedir desta gente extraordinária, que nos tinha recebido magnificamente.</p>
        <p>Começamos a descer às montanhas pela pista, e só nesse dia nos apercebemos das magníficas paisagens do Alborz: as gargantas com as suas quedas de água, a floresta, a neve nos cumes dos picos e a nossa pista em terra que serpenteava as montanhas. Era um cenário fantástico!</p>
        <p>Entrados no asfalto, rapidamente saímos dele e tornamos a entrar noutra pista que nos ia levar para Denili situada a 3690 metros de altitude. A pista era uma sequência de curvas com inclinação bastante acentuada e começou a chover o que dificultou mais ainda a progressão mas os fatos Dainese em Gore-Tex protegiam-nos da chuva.</p>
        <p>Quando chegamos ao ponto mais alto na pista estávamos em Denili, e que o nosso angulo de visão podia apanhar era uma sequência de cumes de uma beleza extraordinária.</p>

        <h2>Teerão Caótica</h2>
        <p>Estávamos a vinte quilómetros de Teerão e para nosso espanto conseguimos visualizar a nuvem de fumo que pairava sobre a cidade... era poluição!</p>
        <p>Entramos em Teerão durante a tarde, estava um calor infernal e o transito era caótico. Teerão tem 10 milhões de habitantes. Mesmo circulando em motociclo era difícil progredir no meio do transito e de vez em quando sentíamos os carros tocarem nas malas das BMW.</p>
        <p>Teerão foi o centro da revolução islâmica iraniana, a primeira do seu género no mundo, com uma poluição crónica e sem nenhum plano de urbanização, o que leva quem chega a Teerão , independentemente do tipo de transporte, a dizer que está tudo louco, pois não existe qualquer regra ( como no resto do País ).</p>
        <p>Pensámos ficar dois dias , mas depois da dificuldade que tivemos em deslocarmo-nos, bem como a poluição permanente, decidimos partir no dia seguinte.</p>
        <p>Na manhã seguinte partimos para nordeste em direcção a Gorgan situada no turquemenistão iraniano. Depois de já termos feito umas centenas de quilómetros, decidimos rolar por uma estrada secundária mais perto da costa do mar Cáspio. De repente começou a surgir arame farpado, estávamos numa zona militar; apercebemo-nos quando vimos militares a correrem para os ninhos de metralhadoras. Passados alguns minutos tínhamos uma patrulha connosco. Pediram-nos os passaportes, explicamos que queríamos seguir para Gorgan junto ao mar, foi-nos dito que era impossível, devido a ser zona militar, e que teríamos de fazer quarenta quilómetros no sentido oposto. Deixaram-nos seguir viagem , não sem antes o oficial comunicar para a torre para nos deixar passar. Não ganhamos para o susto, pois a nossa viagem podia ter acabado ali.</p>
        <p>Chegámos a Gorgan situada a nordeste das montanhas Alborz e asudoeste da fronteira da antiga Republica Soviética do Turquemenistão, que foi ao longo da sua história, o último posto de segurança da civilização persa. Prosseguimos para Shorud, última cidade antes de fazermos a travessia do deserto do sal (Dash-é-Kevir), onde pernoitamos.</p>
        <p>Aproveitamos para fazer uma revisão do material, além das verificações diárias, enchemos os dois jerry-can de 10 litros com gasolina e levamos também 30 litros de agua, pois o deserto não permite erros. Tínhamos já feito cerca de 8 000 quilómetros sem qualquer problema, as BMW R 1100 GS, estavam prontas para o desafio e para demonstrar que foram construídas para este tipo de aventura.</p>
        <p>Partimos ao nascer do sol, tínhamos à nossa frente o famoso deserto do sal (Dash-é-Kavir). Era impressionante a sequência de cadeias rochosas que tínhamos pela frente. Eram 80 quilómetros de pista que tínhamos de fazer até a aldeia de Mo´alleman onde voltaríamos ao asfalto. Esta ligação iria revelar-se terrível, pois o piso era uma mistura de terra, areia e jogas de tamanho pequeno, o calor era imenso (37º graus), o peso das motas e ao vento que soprava forte, formavam um cocktail incrível. Demorámos cerca de quatro horas para fazer este trajecto , no final em Moálleman estávamos exaustos. Aproveitamos o convite de um aldeão para comermos e descansarmos. O senhor Mussa ofereceu-nos em sua casa comida e aproveitamos para descansar. Viemos a saber que tinha dezassete filhos e quando lhe dissemos que cada um de nos tinha um apenas, ficou um pouco surpreendido; apresentou-nos dez dos dezassete filhos. Agradecemos a comida e desejamos que Deus os protegesse ( Motashakkeram, Salãm Aleikom ). Tínhamos de prosseguir viagem, ainda faltavam cerca de 200 quilómetros para sairmos do deserto do sal ( Dash-é-Kevir), tínhamos agora uma estrada de gravilha e a paisagem tinha um aspecto lunar e ao mesmo tempo dantesca, pois o calor era sufocante.</p>

        <h2>Coca-Cola Amarela</h2>
        <p>Começamos a cruzar-nos com camiões, os quais paravam para saber de onde éramos, ofereciam água, cola, chá. Tudo fresco. A bebida preferida era de cor amarela. De inicio não percebemos o que era. Só depois ficamos a saber tratar-se de Coca-Cola na versão iraniana. Ao longo do deserto fomos travando conhecimento com alguns dos camionistas que se sentiam atraídos pelas BMW; todos queriam tirar fotos montados nelas.</p>
        <p>Saímos do deserto, quando avistamos Chah Malek ao fim da tarde, o nosso objectivo era Naim, que ficava a cerca de 200 quilómetros e onde desejávamos pernoitar. Rolamos até Naim e no primeiro hotel que vimos paramos; o dia tinha sido demolidor.</p>

        <h2>Zoroastro</h2>
        <p>O nosso próximo objectivo era Yazd, que fica situada entre o deserto do sal (Dash-é-Kevir), e o deserto de areia (Dash-é-Lut), importante centro pré-islâmico Zoroastriano.</p>
        <p>Chegados a Yazd, fomos visitar o templo do fogo zoroastriano (Ateskkadè), onde a chama sagrada se mantém acesa desde 470 A.D. A imagem da chama a arder dava-nos uma sensação espaço temporal tão imenso, que nos sentíamos minúsculos naquela sala (junto da chama sagrada).</p>
        <p>Aproveitámos também para ver a prisão de Alexandre, O Grande (Zendar-e-Eskandar) que neste momento é uma escola de teologia. Devia ter sido um local semelhante às piores masmorras medievais da Europa.</p>
        <p>Fomos também ver o túmulo dos 12 Emans (Maghbané-yé-Davazdah eman), onde existe uma fina inscrição seljudiça com os nomes de cada Eman, estando nove deles sepultados naquele local. Aproveitamos depois para dar uma volta pela cidade e visitar um dos muitos jardins onde os iranianos tem o saudável hábito de fazer piqueniques.</p>

        <h2>Orange Country</h2>
        <p>À saída da cidade mais um controle dos guardas da revolução: Passeport? Where do you come from? Portugal! Orange country! Finalmente soubemos a razão porque quando parávamos e nos perguntavam de onde éramos, respondiam sempre "orange country", e riam-se.</p>
        <p>Das laranjas, eu explico: os portugueses quando estiveram em Ormuz, introduziram a laranja na Pérsia, obviamente o nome da laranja em farsi, é Portughãl. A partir deste dia quando nos perguntavam de onde éramos, respondíamos em primeiro lugar: Orange Country e riamos também, depois Portugal era uma gargalhada geral.</p>

        <h2>Ormuz</h2>
        <p>Seguimos para sul, o nosso objectivo era Bandar-é-Abbas a 825 quilómetros, situada no Golfo Pérsico. Tínhamos sido avisados que na região de Bandar-é-Abbas o calor era insuportável. Ainda faltavam cerca de 130 quilómetros quando sentimos que tínhamos entrado nela. Foi um autentico choque térmico; parecia irreal, os nossos corpos desidratavam-se a uma velocidade alucinante. Estávamos completamente encharcados em suor. Estavam 45º graus e 90% de humidade e passar nos túneis de montanha era um sacrifício, pois não tinham ventilação. Chegamos a Bandar-é-Abbas, ficamos no primeiro hotel que vimos. Abençoado hotel , tinha ar condicionado!</p>
        <p>Bandar-é-Abbas, a quem os Portugueses chamaram Porto Camerom, por causa dos camarões. Ironicamente o ponto mais alto na historia de Bandar-é-Abbas foi durante a guerra Irão-Iraque, porque os outros portos a norte eram perigosos para a navegação.</p>
        <p>Na manhã seguinte dirigimo-nos para o porto a fim de apanhar a lancha para a ilha de Ormuz. A ligação demorou cerca de 45 minutos, a temperatura subia rapidamente. Ao largo da ilha começamos a avistar o Forte Português.</p>
        <p>Em 1507, o Almirante do Reino de Portugal e dos Algarves, Afonso de Albuquerque, com o objectivo de estabelecer uma base de apoio a Goa, Aden e Malaca, conquistou a ilha e começou a construção da fortaleza que ficou completa em 1515. Os portugueses estiveram em Ormuz até 1622, data em que uma força composta por persas e ingleses tomaram a ilha. A Fortaleza , situada a norte da ilha , tem cerca de 750 metros de largura e é a mais impressionante fortaleza colonial no Irão, apesar de negligenciada pelos visitantes depois depois da revolução. Com efeito, parte dela encontra-se em ruínas pois durante a guerra Irão-Iraque foi bombardeada pala aviação Iraquiana, por ter junto às suas muralhas uma central de telecomunicações, que ficou totalmente destruída.</p>
        <p>Chegados à Bandar-é-Abbas o nosso pensamento era sair dali rapidamente pois o calor era insuportável. Partimos só com 5 litros de gasolina no depósito e 10 litros em cada jerry-can. Uma das estações só tinha diesel e a outra estava fechada; tínhamos conhecimento que a estação de gasolina mais próxima ficava a cerca de 220 quilómetros. Iria ser mesmo à tangente.</p>

        <h2>Persopolis</h2>
        <p>Avistamos Persopolis onde chegamos ao início da tarde. Estávamos a três quilómetros do local e já víamos as colunas do palácio de Darius I (O Grande), cuja construção, deste maciço, magnificente e complexo palácio começou a 331 AC. Alexandre (O Grande), num acto incaracterístico de destruição, pegou fogo a Persopolis, afortunadamente não sem antes transferir a enorme biblioteca para a Grécia. A Grande Entrada, o Portal de Xerxes, a Apadana onde os reis recebiam as visitas, a Parada das Nações mostrando o povo e os animais prestando tributo aos Reis Persas, o Palácio de Darius, o Palácio de Xerxes, um pequeno e interessante museu e o hall de 32 colunas no lado exterior do Portal de Xerxes, onde se esconde o tesouro de Darius são bastantes para merecer uma visita a Persopolis.</p>
        <p>A cerca de quatro quilómetros de Persopolis existe Naghsh-é-Rostam, uma enorme montanha onde foram feitos quatro gigantescos túmulos e onde se acredita que lá estejam sepultados Darius I, Xerxes, Antaxerxes e Darius II.</p>

        <h2>Esfahan</h2>
        <p>Seguimos depois para Esfahan, cidade património mundial ( a nosso ver com razão), onde existe a maior concentração de monumentos do Irão. Esfahan com a sua "Masjed-é-Eman", uma magnifica mesquita e um dos edifícios mais belos do mundo, revestida por dentro e por fora de azulejos em vários tons de azul, com o seu magnifico portal de 30 metros é um exemplo de arquitectura islâmica que combina a azulejaria com a escrita.</p>
        <p>Enquanto visitávamos a mesquita encontramos o David e a Jane, um casal australiano que viajava em dois motociclos desde a Inglaterra até a Austrália. Depois de terem atravessado a Europa e a Turquia encontravam-se agora no Irão. O plano deles era atravessar o Paquistão, Índia, Nepal, Tailândia... enfim, Austrália!</p>
        <p>Entretanto, David tinha já marcado um jogo de futebol entre a selecção Iraniana e a selecção do Resto do Mundo, que era formada por 2 Portugueses, 2 Mexicanos, 1 Inglês, 1 Australiano, 1 Paquistanês, 1 Koweitiano. Foi um jogo bem disputado, o resultado final foi de 4-3 a favor da equipa da casa. A noite em Esfahan é bem movimentada, viemos a saber que a maioria da população anseia por reformas e confia no novo presidente, para os guiar neste difícil caminho, pois os Guardas Revolucionários e os Mullahs ainda detém grande parte do poder. David e a Jane na manhã seguinte partiam com destino ao Paquistão. Despedimo-nos não sem antes trocarmos os nossos E-mails para sabermos as novidades.</p>

        <h2>Hamadan</h2>
        <p>Seguimos para Hamadan, que originalmente se chamou Ecbatana e é uma das cidades mais antigas do mundo. Habitada desde o segundo milénio antes de Cristo, o seu ponto mais alto foi durante o reinado achemita, quando foi capital de verão do império. Vimos o famoso Leão de Alexandre (Sang-é-Shir),actualmente bastante deteriorado devido à erosão.</p>
        <p>Fomos a Ganjnãmé onde se encontra o famoso par de paginas de um livro esculpido na rocha no reinado achemita,sendo uma de Darius e outra de Xerxes. Escritas em Pahlavi e em akkadia, descrevem os impérios e os títulos que aqueles ostentavam. Junto encontra-se também uma bela e refrescante cascata.</p>
        <p>Partimos de Hamadan com destino ao lago Õrumié, que tem uma particularidade: a sua quantidade de sal é tão elevada, que se iguala ao Mar Morto. Não dispensamos um banho para verificarmos in loco. Mergulhamos no lago, e logo um grupo de iranianos que tomava banho começou a agitar os braços e a atirar pepinos para a água, explicando-nos que era para esfregar na face por causa do sal. A sua acção era deveras eficaz,acalmando o ardor na cara.</p>
        <p>Por todo País as pessoas mostravam um espirito de entre ajuda, transmitindo uma sensação de pureza e bem-estar, que nos fazia sempre bem. Nas mais de duzentas paragens que efectuámos, nunca nos pediram osdocumentos, excepto o passaporte.</p>
        <p>Rolamos depois em direcção à fronteira de Bazargan, pois o visto era apenas de 15 dias. Chegamos à fronteira e demoramos cerca de 2 horas para nos despedirmos com saudade destes dias passados com um povo hospitaleiro, simpático, tolerante, e com um carácter que muitos outros povos já esqueceram.</p>

        <h2>O Regresso</h2>
        <p>Depois foi atravessar a Turquia , seguimos com direcção a Istambul onde o turismo de massas nos fez sentir a delicadeza de cidades como Esfahan, Yazd ,Shiraz. Atravessamos o Bósforo e seguimos para a Grécia para o porto de Igoumenitsa, onde embarcamos no ferry para Brindisi , no sul de Itália. Rolámos depois durante dias até à nossa cidade Invicta.</p>
        <p>Tínhamos feito 18.026 km sem problema algum, as BMW estavam à altura das suas tradições, os Metzeler Enduro 4 tinham sido excelentes.</p>
        <p>Agradecemos ao Bruno Soares e à Natacha Soares em particular, às empresas patrocinadoras o apoio incondicional prestado, sem, o qual não poderíamos ter concretizado esta viagem.</p>


    </x-margins-text>
</x-guestLayout>
